version: '3.7'

services:
  XXXXXX:
    image: YYYYYY
    networks:
      - ZZZZZZ
    deploy:
      labels:
        - "traefik.http.routers.XXXXXX.rule=Host(`nginx.homelab`)"
        - "traefik.http.routers.XXXXXX.service=XXXXXX"
        - "traefik.http.services.XXXXXX.loadbalancer.server.port=80"
        - "traefik.docker.network=ZZZZZZ"
#      mode: global
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  ZZZZZZ:
    external: true
